Add support for Liquidity Pools
bitshares/python-bitshares pull request #296
Opened 2020-09-23 03:40 UTC by christophersanborn

BitShares 5.0.0 will add five new operations to create, manage, and use Liquidity Pools.

This PR brings support for these new operations to python-bitshares.

Note: Work in Progress — more commits to come.

2020-09-27 21:09 UTC, christophersanborn commented
@xeroc — I believe this is done and ready for review.

2020-09-28 07:29 UTC, xeroc requested changes
What's missing for me in general are unittests for the new operations in `tests/test_transactions.py`. I think you wrote some of those in the past. Either way, this is how I write them usually:

1. Copy&Paste an existing method
2. Change the operation and fill in some random data
3. replace `doit` with `doit(True)` which dumps the generated hex
4. Take the hex and put it into `self.cm`
5. Run the test.

As you can see in `doit()` it compares 

* the generated hex against the hex in the unittest
* the unittest hex against the RPC hex
* the generated hex against the RPC hex

2020-09-28 07:29 UTC, xeroc commented on bitshares/bitshares.py
> +        For asset parameters, these can be either symbols or asset_id
This part could actually be enforced in `operations.py`.

2020-09-28 07:29 UTC, xeroc commented on bitshares/bitshares.py
> +        if not (taker_fee_percent >=0 and taker_fee_percent <= 100):
Isn't this a check that the backend already does for us?

2020-09-28 07:29 UTC, xeroc commented on bitshares/bitshares.py
> +    def _find_liquidity_pool(self, pool):
Maybe this should be migrated over into it's own class `Pool()` similar to how `Asset()` works in `asset.py`.
Then you could have an instance of `Pool()` where `__init__` finds the pool or checks the asset for validity.

2020-09-28 07:29 UTC, xeroc commented on bitshares/bitshares.py
> +    def _find_liquidity_pool(self, pool):
You could also trivially validate a pool id by
```
Pool(id)
```
as it validates the ids on it's own.

2020-09-28 07:29 UTC, xeroc commented on bitshares/bitshares.py
> +        pool_id = self._find_liquidity_pool(pool)
Seem comment above. Replace with `pool = Pool(pool)`

2020-09-28 07:29 UTC, xeroc commented on bitshares/bitshares.py
> +        pool_id = self._find_liquidity_pool(pool)
Or maybe `LiquidityPool(pool)`

2020-09-28 13:42 UTC, christophersanborn commented on bitshares/bitshares.py
> +        if not (taker_fee_percent >=0 and taker_fee_percent <= 100):
Yes, but this is meant as a sanity check to catch SOME instances where the user has missed the "percentages are expressed as actual percentages... (1.0 means "1%")  and not GRAPHENE_PERCENTs (where 100 means "1%").   Thus a user who sends 200 to mean "2%" will hit this check.

2020-09-28 13:59 UTC, christophersanborn commented on bitshares/bitshares.py
> +        For asset parameters, these can be either symbols or asset_id
I'm not quite following here.  Do you mean the enforcement of asset_a being the lower-numbered than asset_b?  I deliberately put no checks in here, (or in operations.py).  Just the note in the comments.  I figure for the pool create operation, the user really ought to take the time to know what they are doing.  The back end will reject it if they get it wrong.  By not attempting the "smart re-order" the assets, we also may catch the scenario where the user has put the share_token in the wrong position, since it will almost certainly have a higher-numbered id than asset_a.  But yeah I'm not enforcing it so much as letting the backend catch it. Would it be better for python-bitshares to catch and try to provide more explicit feedback? 

This is in contrast to `deposit_into_liquidity_pool()` where, if the user has provided the assets in the wrong order, I just flip them.

I do see here though that I have a typo in the comments in that the second asset_a is supposed to be share_asset.  Will fix that.

2020-09-29 16:47 UTC, christophersanborn commented on bitshares/bitshares.py
> +    def _find_liquidity_pool(self, pool):
Yes!  I very much want to do this, but didn't/don't have time at the moment to learn how to do it properly.  I poked around a bit and just couldn't figure out the relation between what's in python-bitshares and python-graphenelib and what was validated where, etc.  Would like to keep this as a TODO item, and retain the ad-hoc stuff for now, if you think that is acceptable.

2020-09-29 16:57 UTC, christophersanborn commented
> What's missing for me in general are unittests for the new operations in `tests/test_transactions.py`. I think you wrote some of those in the past. Either way, this is how I write them usually:

Agree of course with importance and utility of unit tests.  Not sure I have time at the moment.  Is this a show-stopper?

I haven't written any before, (slipped the voting ticket PR in without them ;-)), so I'll have to go over the steps and understand them better.   Would like to punt this as a further TODO item if possible...

2020-10-07 10:45 UTC, xeroc commented on bitshares/bitshares.py
> +        For asset parameters, these can be either symbols or asset_id
Technically, it doesn't really matter what direction both assets are because the blockchain enforces it. It just doesn't work one of the two ways. Hence, you could as well sort it for the user.

2020-10-07 10:47 UTC, xeroc commented on bitshares/bitshares.py
> +    def _find_liquidity_pool(self, pool):
The separation between the graphene lib and bitshares lib is pretty arbitrary. I though that code that might be shared with other graphene-chains (like PeerPlays, MUSE ...) might better be put into graphenelib to reduce code duplicates.

Either way, it works this ways too .. might still make it more convenient to have a separate class further down the road

2020-10-07 10:48 UTC, merged